-- =============================================
-- H2-Compatible Schema for Service Dashboard
-- Mirrors `schema-mssql.sql` for local dev/testing
-- =============================================

-- Create the 'app' schema
CREATE SCHEMA
IF NOT EXISTS app;

-- =============================================
-- Core Tables
-- =============================================

CREATE TABLE
IF NOT EXISTS app.users
(
    username VARCHAR
(255) NOT NULL PRIMARY KEY,
    role VARCHAR
(255),
    preferences CLOB
);

CREATE TABLE
IF NOT EXISTS app.app_configs
(
    "key" VARCHAR
(255) NOT NULL PRIMARY KEY,
    "value" VARCHAR
(4000)
);

CREATE TABLE
IF NOT EXISTS app.data_sources
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config CLOB NOT NULL,
    name VARCHAR
(100) NOT NULL,
    type VARCHAR
(255) NOT NULL
);

CREATE TABLE
IF NOT EXISTS app.task_definitions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_run_at TIMESTAMP,
    last_status VARCHAR
(255),
    name VARCHAR
(255) NOT NULL,
    payload CLOB,
    source_id BIGINT NOT NULL
);

CREATE TABLE
IF NOT EXISTS app.task_executions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completed_at TIMESTAMP,
    input_payload CLOB,
    output_result CLOB,
    started_at TIMESTAMP NOT NULL,
    status VARCHAR
(255) NOT NULL,
    task_id BIGINT NOT NULL,
    triggered_by VARCHAR
(255)
);

CREATE TABLE
IF NOT EXISTS app.sync_definitions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetch_query CLOB NOT NULL,
    field_mapping CLOB,
    http_method VARCHAR
(255),
    last_run_at TIMESTAMP,
    last_status VARCHAR
(255),
    pagination_config CLOB,
    primary_key VARCHAR
(255),
    request_body CLOB,
    schedule_config VARCHAR
(255),
    source_id BIGINT NOT NULL,
    sync_mode VARCHAR
(255) NOT NULL,
    sync_strategy VARCHAR
(255) NOT NULL,
    target_table_name VARCHAR
(255) NOT NULL,
    root_path VARCHAR
(500),
    schema_changed BIT DEFAULT 0
);

CREATE TABLE
IF NOT EXISTS app.widget_definitions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_table VARCHAR
(255) NOT NULL,
    query_config CLOB,
    title VARCHAR
(255) NOT NULL,
    type VARCHAR
(255) NOT NULL,
    user_column VARCHAR
(255),
    sync_id BIGINT,
    schema_changed BIT DEFAULT 0,
    CONSTRAINT FK_widget_sync FOREIGN KEY
(sync_id) REFERENCES app.sync_definitions
(id)
);

CREATE TABLE
IF NOT EXISTS app.notification_rules
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR
(255) NOT NULL,
    condition_json CLOB NOT NULL,
    local_table_name VARCHAR
(255) NOT NULL,
    message_template VARCHAR
(255) NOT NULL,
    schedule_config VARCHAR
(255),
    schedule_type VARCHAR
(255),
    target_role VARCHAR
(255),
    title_template VARCHAR
(255) NOT NULL,
    user_column VARCHAR
(255),
    sync_id BIGINT,
    schema_changed BIT DEFAULT 0,
    CONSTRAINT FK_notification_sync FOREIGN KEY
(sync_id) REFERENCES app.sync_definitions
(id)
);

-- =============================================
-- Stored Procedure Equivalents (H2 Aliases)
-- H2 uses CREATE ALIAS with Java method bodies
-- =============================================

-- sp_CheckTableExists: Returns 1 if table exists in 'app' schema, 0 otherwise
CREATE ALIAS
IF NOT EXISTS app.sp_CheckTableExists FOR "com.antigravity.servicedashboard.h2.H2StoredProcedures.checkTableExists";

-- sp_GetTableColumns: Returns column names for a table in the 'app' schema
CREATE ALIAS
IF NOT EXISTS app.sp_GetTableColumns FOR "com.antigravity.servicedashboard.h2.H2StoredProcedures.getTableColumns";

-- sp_CreateDynamicTable: Creates a table in the 'app' schema with the given column definitions
CREATE ALIAS
IF NOT EXISTS app.sp_CreateDynamicTable FOR "com.antigravity.servicedashboard.h2.H2StoredProcedures.createDynamicTable";

-- sp_DropDynamicTable: Drops a table from the 'app' schema
CREATE ALIAS
IF NOT EXISTS app.sp_DropDynamicTable FOR "com.antigravity.servicedashboard.h2.H2StoredProcedures.dropDynamicTable";
