package com.antigravity.servicedashboard.h2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.antigravity.servicedashboard.util.MessageUtils;


public class H2StoredProcedures {

    private H2StoredProcedures() {

    }


    public static ResultSet checkTableExists(Connection conn, String tableName) throws SQLException {
        PreparedStatement ps = conn.prepareStatement(
                "SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END "
                + "FROM INFORMATION_SCHEMA.TABLES "
                + "WHERE TABLE_SCHEMA = 'app' AND UPPER(TABLE_NAME) = UPPER(?)");
        ps.setString(1, tableName);
        return ps.executeQuery();
    }


    public static ResultSet getTableColumns(Connection conn, String tableName) throws SQLException {

        if (tableName != null && !tableName.matches("^[a-zA-Z0-9_]+$")) {
            throw new SQLException(MessageUtils.get("error.table.invalid.param", tableName));
        }

        PreparedStatement ps = conn.prepareStatement(
                "SELECT COLUMN_NAME as \"name\" "
                + "FROM INFORMATION_SCHEMA.COLUMNS "
                + "WHERE TABLE_SCHEMA = 'app' AND UPPER(TABLE_NAME) = UPPER(?) "
                + "ORDER BY ORDINAL_POSITION");
        ps.setString(1, tableName);
        return ps.executeQuery();
    }


    public static void createDynamicTable(Connection conn, String tableName, String columnDefinitions)
            throws SQLException {

        if (tableName == null || !tableName.matches("^[a-zA-Z0-9_]+$")) {
            throw new SQLException(MessageUtils.get("error.table.invalid.param", tableName));
        }


        try (PreparedStatement check = conn.prepareStatement(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES "
                + "WHERE TABLE_SCHEMA = 'app' AND UPPER(TABLE_NAME) = UPPER(?)")) {
            check.setString(1, tableName);
            try (ResultSet rs = check.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) {
                    return;
                }
            }
        }

        StringBuilder ddl = new StringBuilder();
        ddl.append("CREATE TABLE \"app\".\"").append(tableName).append("\" (");
        ddl.append("_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ");
        ddl.append("_synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP");
        if (columnDefinitions != null && !columnDefinitions.isBlank()) {
            ddl.append(", ").append(columnDefinitions);
        }
        ddl.append(")");

        try (Statement stmt = conn.createStatement()) {
            stmt.execute(ddl.toString());
        }
    }


    public static void dropDynamicTable(Connection conn, String tableName) throws SQLException {

        if (tableName == null || !tableName.matches("^[a-zA-Z0-9_]+$")) {
            throw new SQLException(MessageUtils.get("error.table.invalid.param", tableName));
        }

        try (Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS \"app\".\"" + tableName + "\"");
        }
    }
}
